version: '3.1'
services:
  wordpress:
    image: wordpress:5.6-php7.4-apache
    restart: on-failure
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  phpmyadmin:
    image: phpmyadmin:5.0-apache
    restart: on-failure
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=exampleuser
      - PMA_PASSWORD=examplepass
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: